### ISSUE TITLE
Redirection FAILS!

### ISSUE THREAD

**Issue by geoffmcl** [geoffmcl/test-console#1]
When I run, in a cmd console  -

```
> test-con2 > temp1.txt 2>&1
```

I get the following output to the console -

```
C:\GTools\ConApps\tests\test-console\build.x64>release\test-con2 >temp1.txt 2>&1

C:\GTools\ConApps\tests\test-console\build.x64>test-con2: AttachConsole succeeded... Done fropen
test-con2: HOut is is a disk file. (type 1) - handle: 00000000000001C4 (-11)
test-con2:3: Output to stdout
test-con2:3: Output to stderr
test-con2: Doing FreeConsole...

C:\GTools\ConApps\tests\test-console\build.x64>
```

Note, this last prompt only appears after I do an `<enter>` key...

And the `temp1.txt only contains -

```
test-con2:1: Output to stdout
test-con2:1: Output to stderr
test-con2:2: Output to stdout
test-con2:2: Output to stderr
```

Definitely the redirection does not hold! What more **mess** needs to be added?

**Comment by jasin** [comment]
Line 75:
`if (type == FILE_TYPE_DISK) {`

should be

`if (type == FILE_TYPE_CHAR) {`

You break file redirection as soon as you call re-open. This should only be done when you want output to console. If std io was already redirected, then preserve it. You do this by NOT calling freopen()

**Comment by geoffmcl** [comment]
@jasin thanks... yes, avoiding `freopen` and the redirection set up by the cmd processor stays in place for that console...

And the prompt is repainted on exit... great... closed...
